# -*- coding: utf-8 -*-
"""graficoEmBarras.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OIcQkP14viBFNX6ZjVu0ZzCguQtBpcr8
"""

#graficos em linhas com titulos

import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [2, 5, 9, 0, 1]
#legenda do grafico / titulo
titulo = "Grafico de barras"
eixox = "Eixo X"
eixoy = "Eixo Y"
plt.title(titulo)

#eixos
plt.xlabel(eixox)
plt.ylabel(eixoy)

#parametros x e y 
#grafico em linha
plt.bar(x, y)

#exibir o grafico
plt.show()